version: "3.3"

services:
  postgres:
    container_name: postgres-db
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1974
      - POSTGRES_DB=sport
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5434:5432

  app:
    container_name: cicd
    image: husniddindocker/cicd
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env
